### ISSUE TITLE
calendar-detail 페이지 연결

### ISSUE THREAD

**Issue by k168ww** [2024-venture-calender/venture-calender#10]
## 🎋 작업중인 브랜치
- feature/eventCalendar, 
- feature/detailToCalendar

## 💡 작업동기
- detail 페이지와의 연동

## 🔑 주요 변경사항
- 기본 설정이 조금 변경되었고, detail 페이지와의 연동을 했습니다.

## 🎉 예상 결과
- 굿

## 📚 참고 사항
- 달력에서 제목이 덜 보이는 것도 있을 것 같은데 괜찮을까요?!

## 🏞 스크린샷
- 
![image](https://github.com/2024-venture-calender/venture-calender/assets/124691590/653bcb65-5b7e-4ec1-8733-c007e7538a87)
![image](https://github.com/2024-venture-calender/venture-calender/assets/124691590/302f3042-a0da-49e3-ae6f-da123a025a45)

## 관련 이슈
- #4

**Comment by k168ww** [comment]
충돌 고치다 보니 사진은 다시 못 담았어요 ㅠ.ㅠ 송은님 브랜치랑 머지 하면 뜰 거예요!!

**Comment by ddoddo1228** [comment]
우와 수고하셨습니다
