### ISSUE TITLE
[develop/CalendarToMain] 메인페이지-이벤트캘린더 간 연결

### ISSUE THREAD

**Issue by do0ik** [2024-venture-calender/venture-calender#11]
## 🎋 작업중인 브랜치
- develop/CalendarToMain

## 💡 작업동기
- 메인페이지에서 이벤트 캘린더로 이동할 수 있도록 한다.

## 🔑 주요 변경사항
- 메인 페이지 캐러셀 상 버튼을 통한 캘린더 이동
- 캘린더 디자인 보완

## 🏞 스크린샷
![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/7c632c87-084b-4c85-bf87-eea08ef5fa5e)

![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/16f63f82-7ef2-4424-9fd5-0e6c111c70aa)

**Comment by se-3-yeon** [comment]
깔끔하고 보기 좋게 잘 되어 있네요!

**Comment by ddoddo1228** [comment]
대박이네요 고생하셨습니다.
