### ISSUE TITLE
[develop/master] 메인-캘린더-상세 페이지 연결

### ISSUE THREAD

**Issue by do0ik** [2024-venture-calender/venture-calender#13]
## 🎋 작업중인 브랜치
- develop/master

## 💡 작업동기
- 캘린더를 통해 이벤트를 확인하고 조회할 수 있도록 함

## 🔑 주요 변경사항
- 상세 페이지 컴포넌트 통합
- 상세 페이지 CSS 모듈화

## 🎉 예상 결과
- 사용자가 이벤트를 조회할 수 있게 됨

## 🏞 스크린샷
![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/53a6e751-a782-47b0-a1b4-31c473e5d755)

![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/647e3412-5b4a-4b97-b7e4-367943628b0e)

**Comment by ddoddo1228** [comment]
정말 고생 많으십니다.. 수고하셨습니다
