### ISSUE TITLE
Login&Register 구현

### ISSUE THREAD

**Issue by inredzero** [2024-venture-calender/venture-calender#14]
## 🎋 작업중인 브랜치
- [feature/Login&Register]

## 🔑 주요 변경사항
- 객체 배열에 저장된 데이터를 로그인할때 되게 했고 회원가입은 그냥 폼만 만들고 따로 데이터 이동 시키는건 못했습니다..
- 이메일이랑 비밀번호는 입력 할때 형식에 맞는 조건에 의해서만 버튼이 활성화 되게 했습니다.

## 📚 참고 사항
- 회원가입 했을때 그 가입한 사용자가 로그인이 되지 않습니다... 

## 🏞 스크린샷
<img width="324" alt="스크린샷 2024-05-05 오후 12 25 12" src="https://github.com/2024-venture-calender/venture-calender/assets/96677474/44f86183-bf1c-49e6-98b8-20b7f8feeff3">

**Comment by se-3-yeon** [comment]
회원가입 기능이 조금 아쉽게 되었지만, 깔끔하게 잘 나오네요!

**Comment by ddoddo1228** [comment]
깔끔하고 괜찮네요 ㅎㅎ
