### ISSUE TITLE
[develop/ListToMaster] 이벤트 리스트 형식 출력 기능 추가

### ISSUE THREAD

**Issue by do0ik** [2024-venture-calender/venture-calender#17]
## 🎋 작업중인 브랜치
- [develop/ListToMaster]

## 💡 작업동기
- 이벤트들을 캘린더 뿐 아니라 목록 형태로 출력 가능하도록 한다.

## 🎉 예상 결과
- 사용자 경험 증대

## 🏞 스크린샷
![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/a526361e-3157-4885-befc-4531161d02cd)

![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/3b6fc29b-2b67-4d32-b23e-a2b72686a4fa)

## 관련 이슈
- EventList.css 모듈화 필요!!

**Comment by ddoddo1228** [comment]
오 이런 기능 좋은 것 같습니다 수고하셨습니다
