### ISSUE TITLE
[hotifx/Detail] 상세페이지 외부 링크 이동 후 뒤로가기 시 로그인 해제 현상

### ISSUE THREAD

**Issue by do0ik** [2024-venture-calender/venture-calender#23]
## 🎋 작업중인 브랜치
- [hotifx/Detail]

## 💡 작업동기
- 바로가기를 통해 외부링크 이동 후 뒤로가기 시 로그인 해제되는 현상이 발생

## 🔑 주요 변경사항
- 새 창을 통해 외부 링크에 접속하도록 할 것

**Comment by inredzero** [comment]
세세한 오류 해결 좋아요!!
