### ISSUE TITLE
[hotfix/Detail] 대문 페이지 이미지 변경

### ISSUE THREAD

**Issue by do0ik** [2024-venture-calender/venture-calender#24]
## 🎋 작업중인 브랜치
- [hotfix/Detail] 

## 🔑 주요 변경사항
- 더미 데이터 이미지를 본 사이트 캡처본으로 교체

## 🏞 스크린샷
![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/476682eb-8d27-4d67-89f9-b61c4c327bf3)

![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/347cb27b-8958-41c1-b221-1e3a5650347e)

**Comment by inredzero** [comment]
미리 보여주는 거 좋은 생각인거 같아요
