### ISSUE TITLE
[feature/mainPage] 메인 페이지 생성

### ISSUE THREAD

**Issue by do0ik** [2024-venture-calender/venture-calender#5]
## 🎋 작업중인 브랜치
- feature/mainPage

## 💡 작업동기
-  URL 최상위 루트 접속 시 출력되는 대문 페이지가 필요

## 🔑 주요 변경사항
- 캐러셀을 통해 사이트의 주요 특징들을 소개

## 🎉 예상 결과
- 사용자가 사이트의 기능과 구조에 대해 쉽게 알 수 있음

## 📚 참고 사항
- 로그인 / 회원가입, 이벤트 캘린더 / 목록 페이지와의 연동 필요

## 🏞 스크린샷
![image](https://github.com/2024-venture-calender/venture-calender/assets/133643805/fc849aaa-4059-4ba3-84eb-ad8d3935464f)

**Comment by k168ww** [comment]
로고도 깔끔하니 예쁘고 메인페이지도 좋네요!!

**Comment by inredzero** [comment]
로고 정말 마음에 들어요 !!

**Comment by ddoddo1228** [comment]
메인페이지가 참 깔끔하고 좋네요
