### ISSUE TITLE
EventList - 이벤트 목록 출력

### ISSUE THREAD

**Issue by se-3-yeon** [2024-venture-calender/venture-calender#6]
## 🎋 작업중인 브랜치
- feature/eventList

## 💡 작업동기
- 이벤트의 목록을 출력.

## 🔑 주요 변경사항
- EventList 페이지 추가

## 🎉 예상 결과
- 이벤트의 목록들이 출력됨.

## 📚 참고 사항
- 메인페이지, 상세 페이지 연결 필요.

## 🏞 스크린샷
![목록](https://github.com/2024-venture-calender/venture-calender/assets/82174047/fcac0fef-e271-4ec9-bb7f-0a63848aa8c1)

**Comment by k168ww** [comment]
둥글둥글해서 예쁜 것 같아요 수고하셨습니다~!!

**Comment by inredzero** [comment]
그림자 넣어서 입체감 있게 보이네요!! 좋아요

**Comment by ddoddo1228** [comment]
입체감 있고 이쁘네요
