### ISSUE TITLE
이벤트 상세 페이지 생성

### ISSUE THREAD

**Issue by ddoddo1228** [2024-venture-calender/venture-calender#7]
## 🎋 작업중인 브랜치
- feature/Detail

## 💡 작업동기
- 이벤트 상세 페이지로 원하는 이벤트에 대한 자세한 내용을 알기 위해

## 🔑 주요 변경사항
- 이벤트 사진, 상세 내용, 태그 및 구글맵api로 행사 위치 띄움

## 🎉 예상 결과
- 이벤트에 대한 자세한 정보를 알 수 있음.

## 📚 참고 사항
- 태그 변경, 목록 페이지와 연동 필요, 로고 사진 넣어야 함

## 🏞 스크린샷
- 
![스크린샷 2024-05-04 190701](https://github.com/2024-venture-calender/venture-calender/assets/135615995/9adcd329-5284-4512-b855-8e4f28ee8def)
![스크린샷 2024-05-04 190719](https://github.com/2024-venture-calender/venture-calender/assets/135615995/bf2081e4-609e-4442-a057-829a89eee4c0)

**Comment by k168ww** [comment]
우와 바로 배포해도 될만큼 깔끔하네요!!

**Comment by inredzero** [comment]
깔끔하게 잘 하셨네요 고생했어요!
