### ISSUE TITLE
EventList - 검색 기능 추가

### ISSUE THREAD

**Issue by se-3-yeon** [2024-venture-calender/venture-calender#9]
## 🎋 작업중인 브랜치
- feature/eventList

## 💡 작업동기
- 검색 기능

## 🔑 주요 변경사항
- 이벤트 목록 내용 변경
- 검색 기능 추가

## 🎉 예상 결과
- 검색창에 찾고자 하는 이벤트의 타이틀을 적으면 해당되는 이벤트목록이 뜸.

## 📚 참고 사항
- 메인페이지, 상세 페이지 연결 필요.

## 🏞 스크린샷
![검색추가](https://github.com/2024-venture-calender/venture-calender/assets/82174047/142df119-a76b-4177-981a-53aa8b09aeb9)

**Comment by k168ww** [comment]
어려운 기능이었을텐데 수고 많으셨습니다!!

**Comment by inredzero** [comment]
검색기능 좋네요!!

**Comment by ddoddo1228** [comment]
우와 검색기능까지 하셨네요 좋아요
